#!/bin/bash

echo "================================================"
echo "🔧 CONFIGURAR GOOGLE SHEETS PARA EL BOT"
echo "================================================"
echo ""
echo "📊 Tu Google Sheet ID está listo:"
echo "   1nsV6uAHE-U4Tz-uLYoIroDYcP84GdQj7uhrflXP-irQ"
echo ""
echo "❌ PROBLEMA DETECTADO:"
echo "   El valor actual en GOOGLE_SERVICE_ACCOUNT_KEY"
echo "   es un token de Telegram Bot, no de Google"
echo ""
echo "✅ SOLUCIÓN - Sigue estos pasos:"
echo ""
echo "1️⃣ OPCIÓN A: Si tienes el bot de Telegram con Sheets"
echo "   ----------------------------------------"
echo "   a) Busca el archivo JSON del Service Account"
echo "      que usa el bot de Telegram"
echo "   b) Cópialo a esta carpeta"
echo "   c) Ejecuta:"
echo "      cat tu-archivo.json | tr -d '\n' | pbcopy"
echo "   d) Edita .env y pega después de GOOGLE_SERVICE_ACCOUNT_KEY="
echo ""
echo "2️⃣ OPCIÓN B: Crear nuevo Service Account"
echo "   ----------------------------------------"
echo "   a) Ve a: https://console.cloud.google.com"
echo "   b) Crea un proyecto nuevo (o usa uno existente)"
echo "   c) Busca 'Service Accounts'"
echo "   d) Crea uno nuevo con rol 'Editor'"
echo "   e) Descarga el JSON"
echo "   f) Ejecuta:"
echo "      cat credentials.json | tr -d '\n' | pbcopy"
echo "   g) Pega en .env"
echo ""
echo "3️⃣ COMPARTIR EL SHEET"
echo "   ----------------------------------------"
echo "   a) Abre: https://docs.google.com/spreadsheets/d/1nsV6uAHE-U4Tz-uLYoIroDYcP84GdQj7uhrflXP-irQ"
echo "   b) Click en 'Compartir'"
echo "   c) Busca 'client_email' en el JSON"
echo "   d) Copia ese email"
echo "   e) Pégalo en 'Compartir' con permisos de 'Editor'"
echo ""
echo "📝 EJEMPLO DE JSON CORRECTO:"
echo '{"type":"service_account","project_id":"mi-proyecto","private_key_id":"abc123","private_key":"-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n","client_email":"bot@proyecto.iam.gserviceaccount.com","client_id":"123456789"}'
echo ""
echo "🚀 Una vez configurado, reinicia el bot:"
echo "   node bot-final.js"
echo ""
echo "================================================"
