#!/bin/bash

echo "📱 Configurando notificaciones a grupos de WhatsApp"
echo "================================================="
echo ""
echo "PASO 1: OBTENER EL ID DEL GRUPO"
echo "--------------------------------"
echo "1. En WhatsApp Web o la app, crea un grupo o usa uno existente"
echo "2. Agrega el número de Twilio al grupo (+14155238886)"
echo "3. Envía un mensaje desde el grupo al bot"
echo "4. En los logs de Heroku verás algo como:"
echo "   📨 Mensaje recibido de whatsapp:+14155238886-1234567890@g.us"
echo "   El ID del grupo es: whatsapp:+14155238886-1234567890@g.us"
echo ""
echo "PASO 2: CONFIGURAR VARIABLES EN HEROKU"
echo "---------------------------------------"
echo "Ejecuta estos comandos con el ID de tu grupo:"
echo ""
echo "# Para grupo de administración principal:"
echo "heroku config:set WHATSAPP_ADMIN_GROUP='whatsapp:+14155238886-XXXXXXXXXX@g.us' -a cafe-bot-whatsapp"
echo ""
echo "# Para notificar a un número individual (administrador):"
echo "heroku config:set WHATSAPP_ADMIN_NUMBER='whatsapp:+51999999999' -a cafe-bot-whatsapp"
echo ""
echo "# Opcional - Para grupo de ventas:"
echo "heroku config:set WHATSAPP_VENTAS_GROUP='whatsapp:+14155238886-YYYYYYYYYY@g.us' -a cafe-bot-whatsapp"
echo ""
echo "# Opcional - Para grupo de producción (pedidos grandes):"
echo "heroku config:set WHATSAPP_PRODUCCION_GROUP='whatsapp:+14155238886-ZZZZZZZZZZ@g.us' -a cafe-bot-whatsapp"
echo ""
echo "PASO 3: HACER PUSH DE LOS CAMBIOS"
echo "----------------------------------"
echo "git add notification-service.js bot-final.js"
echo "git commit -m 'Agregar notificaciones a grupos de WhatsApp'"
echo "git push heroku main"
echo ""
echo "PASO 4: VERIFICAR"
echo "-----------------"
echo "heroku logs --tail -a cafe-bot-whatsapp"
echo ""
echo "📊 NOTIFICACIONES QUE SE ENVIARÁN:"
echo "-----------------------------------"
echo "✅ Nuevo pedido recibido"
echo "✅ Comprobante de pago recibido"
echo "✅ Pedidos grandes (>50kg) a producción"
echo "✅ Resumen diario (opcional)"
echo ""
echo "💡 EJEMPLO DE NOTIFICACIÓN:"
echo "----------------------------"
echo "🆕 NUEVO PEDIDO"
echo "━━━━━━━━━━━━━"
echo "📋 ID: CAF-123456"
echo "🕐 Hora: 14:30"
echo ""
echo "CLIENTE:"
echo "🏢 Cafetería Central"
echo "👤 Juan Pérez"
echo "📱 +51987654321"
echo "📍 Av. Principal 123, Miraflores"
echo ""
echo "PEDIDO:"
echo "☕ Café Premium"
echo "⚖️ 20 kg"
echo "💰 Total: S/1000"
echo ""
echo "PAGO:"
echo "💳 Transferencia"
echo "📸 Comprobante: ✅"
