#!/bin/bash

echo "==========================================="
echo "🚀 DEPLOY FINAL - COLUMNAS CORREGIDAS"
echo "==========================================="
echo ""
echo "✅ ARCHIVOS MODIFICADOS:"
echo "------------------------"
echo "1. bot-final.js - Con imports y funciones corregidas"
echo "2. sheets-funciones-corregidas.js - Funciones con orden correcto"
echo ""
echo "==========================================="
echo ""
echo "📊 VERIFICAR EN GOOGLE SHEETS ANTES:"
echo "------------------------------------"
echo ""
echo "HOJA: PedidosWhatsApp (20 columnas)"
echo "A: ID_Pedido"
echo "B: Fecha"
echo "C: Hora"
echo "D: Empresa"
echo "E: Contacto"
echo "F: Telefono"
echo "G: Direccion"
echo "H: Producto"
echo "I: Cantidad_kg"
echo "J: Precio_Unitario"
echo "K: Subtotal"
echo "L: Descuento"
echo "M: Total"
echo "N: Metodo_Pago"
echo "O: Estado          ← COLUMNA CRÍTICA"
echo "P: URL_Comprobante"
echo "Q: Observaciones"
echo "R: Tipo_Pedido"
echo "S: ID_Cliente"
echo "T: Usuario_WhatsApp ← ÚLTIMA COLUMNA"
echo ""
echo "HOJA: Clientes (15 columnas)"
echo "A: ID_Cliente"
echo "B: WhatsApp"
echo "C: Empresa"
echo "D: Nombre_Contacto"
echo "E: Telefono_Contacto"
echo "F: Email"
echo "G: Direccion"
echo "H: Distrito"
echo "I: Ciudad"
echo "J: Fecha_Registro"
echo "K: Ultima_Compra"
echo "L: Total_Pedidos"
echo "M: Total_Comprado"
echo "N: Total_Kg"
echo "O: Notas"
echo ""
echo "==========================================="
echo ""
echo "📋 COMANDOS PARA HACER PUSH:"
echo "----------------------------"
echo ""
echo "# Verificar estado"
echo "git status"
echo ""
echo "# Agregar archivos"
echo "git add bot-final.js sheets-funciones-corregidas.js"
echo ""
echo "# Commit"
echo 'git commit -m "Fix completo: Orden correcto de columnas en Google Sheets'
echo ""
echo "# - bot-final.js actualizado con funciones corregidas"
echo "# - Columnas A-T en orden correcto"
echo "# - Estado en columna O"
echo "# - WhatsApp en columna T"
echo "# - Guardar clientes separadamente"
echo "# - Actualización de estados funcional"
echo '# - Notificaciones con links de comprobantes"'
echo ""
echo "# Push a Heroku"
echo "git push heroku main"
echo ""
echo "==========================================="
echo ""
echo "🔍 DESPUÉS DEL DEPLOY:"
echo "----------------------"
echo ""
echo "1. Verificar logs:"
echo "   heroku logs --tail -a cafe-bot-whatsapp"
echo ""
echo "2. Hacer una prueba completa:"
echo "   - Enviar 'hola'"
echo "   - Hacer un pedido"
echo "   - Enviar comprobante"
echo "   - Verificar que se guarde correctamente en Sheets"
echo ""
echo "3. Verificar en Google Sheets que:"
echo "   - Los datos estén en las columnas correctas"
echo "   - El estado esté en columna O"
echo "   - El WhatsApp esté en columna T"
echo ""
echo "==========================================="
echo ""
echo "✅ SISTEMA LISTO PARA PRODUCCIÓN"
echo ""
echo "==========================================="
