#!/bin/bash

echo "📁 Script para crear nueva carpeta en Google Drive"
echo "=================================================="
echo ""
echo "PASOS MANUALES EN GOOGLE DRIVE:"
echo ""
echo "1️⃣ Ve a Google Drive: https://drive.google.com"
echo ""
echo "2️⃣ Crea una nueva carpeta llamada: COMPROBANTES_BOT"
echo ""
echo "3️⃣ Haz clic derecho en la carpeta > Compartir"
echo ""
echo "4️⃣ En 'Añadir personas y grupos' pega este email:"
echo "   cafe-bot@maximal-journey-459103-k4.iam.gserviceaccount.com"
echo ""
echo "5️⃣ Selecciona rol: Editor"
echo ""
echo "6️⃣ Haz clic en 'Enviar'"
echo ""
echo "7️⃣ Abre la carpeta y copia el ID de la URL:"
echo "   https://drive.google.com/drive/folders/[ESTE_ES_EL_ID]"
echo ""
echo "8️⃣ Actualiza las variables en Heroku con el nuevo ID:"
echo ""
echo "heroku config:set DRIVE_FOLDER_ID=NUEVO_ID_AQUI DRIVE_COMPROBANTES_ID=NUEVO_ID_AQUI -a cafe-bot-whatsapp"
echo ""
echo "9️⃣ Reinicia la aplicación:"
echo "heroku restart -a cafe-bot-whatsapp"
echo ""
echo "🔟 Verifica los logs:"
echo "heroku logs --tail -a cafe-bot-whatsapp"
