#!/bin/bash

echo "==========================================="
echo "🔧 FIX CRÍTICO: USUARIO WHATSAPP"
echo "==========================================="
echo ""
echo "PROBLEMA CORREGIDO:"
echo "-------------------"
echo "❌ ANTES: Guardaba el teléfono que el cliente ingresaba en el chat"
echo "✅ AHORA: Guarda el WhatsApp de la sesión (from)"
echo ""
echo "==========================================="
echo ""
echo "ESTRUCTURA DE DATOS CORRECTA:"
echo "------------------------------"
echo ""
echo "COLUMNA F (Telefono):"
echo "→ El número que el cliente INGRESA en el chat"
echo "→ Ejemplo: '987654321' (lo que escribe)"
echo ""
echo "COLUMNA T (Usuario_WhatsApp):"
echo "→ El número de WhatsApp de la SESIÓN (from)"
echo "→ Ejemplo: '935923492' (de donde escribe)"
echo "→ ESTE ES EL IDENTIFICADOR ÚNICO"
echo ""
echo "==========================================="
echo ""
echo "CÓMO FUNCIONA AHORA:"
echo "--------------------"
echo ""
echo "1. CUANDO GUARDA UN PEDIDO:"
cat << 'CODE'
await agregarPedidoCorregido(googleSheets, {
    id: pedidoId,
    empresa: userState.data.empresa,
    contacto: userState.data.contacto,
    telefonoContacto: userState.data.telefono,  // Lo que ingresó el cliente
    whatsappSesion: from,                        // DE DONDE ESCRIBE (sesión)
    direccion: userState.data.direccion,
    // ... resto de datos
});
CODE
echo ""
echo "2. EN GOOGLE SHEETS SE GUARDA:"
echo "   Columna F: '987654321' (lo que escribió)"
echo "   Columna T: '935923492' (desde donde escribió)"
echo ""
echo "3. PARA BUSCAR CLIENTES Y PEDIDOS:"
echo "   SIEMPRE usa la columna T (Usuario_WhatsApp)"
echo "   Porque es el número real de la sesión"
echo ""
echo "==========================================="
echo ""
echo "HOJA CLIENTES:"
echo "--------------"
echo "Columna B (WhatsApp): También debe ser el 'from'"
echo "Columna E (Telefono_Contacto): Lo que ingresa el cliente"
echo ""
echo "HOJA PEDIDOSWHATSAPP:"
echo "---------------------"
echo "Columna F (Telefono): Lo que ingresa el cliente"
echo "Columna T (Usuario_WhatsApp): El 'from' de la sesión ← IDENTIFICADOR"
echo ""
echo "==========================================="
echo ""
echo "BENEFICIOS:"
echo "-----------"
echo "✅ Identifica correctamente al cliente"
echo "✅ No importa qué teléfono ingrese"
echo "✅ Siempre encuentra sus pedidos anteriores"
echo "✅ Datos de cliente siempre correctos"
echo "✅ No duplica clientes"
echo ""
echo "==========================================="
echo ""
echo "COMANDOS PARA DEPLOY:"
echo "---------------------"
echo ""
echo "git add sheets-funciones-corregidas.js bot-final.js"
echo ""
echo 'git commit -m "Fix crítico: Usuario WhatsApp desde sesión'
echo ""
echo "- Columna T siempre guarda el from (sesión)"
echo "- Columna F guarda el teléfono ingresado"
echo "- Identificación correcta de clientes"
echo '- No importa qué teléfono ingresen"'
echo ""
echo "git push heroku main"
echo ""
echo "==========================================="
echo ""
echo "PARA VERIFICAR:"
echo "---------------"
echo ""
echo "1. Hacer un pedido"
echo "2. Revisar en Sheets:"
echo "   - Columna T debe tener el WhatsApp real (935923492)"
echo "   - Columna F puede tener otro número (el ingresado)"
echo ""
echo "3. Hacer otro pedido con el mismo WhatsApp:"
echo "   - Debe reconocer al cliente"
echo "   - Debe mostrar sus datos guardados"
echo ""
echo "==========================================="
