#!/bin/bash

echo "==========================================="
echo "🔧 FIX: NORMALIZACIÓN DE NÚMEROS"
echo "==========================================="
echo ""
echo "CAMBIOS REALIZADOS:"
echo "-------------------"
echo ""
echo "✅ Al GUARDAR pedidos:"
echo "   - Quita 'whatsapp:'"
echo "   - Quita '+51'"
echo "   - Deja solo números: 936934501"
echo ""
echo "✅ Al BUSCAR pedidos:"
echo "   - Normaliza igual el número de búsqueda"
echo "   - Normaliza los números en Sheets"
echo "   - Compara: 936934501 == 936934501 ✅"
echo ""
echo "==========================================="
echo ""
echo "ACCIÓN MANUAL EN GOOGLE SHEETS:"
echo "--------------------------------"
echo ""
echo "En la columna T del pedido existente:"
echo "Cambiar: +51936934501"
echo "Por:     936934501"
echo ""
echo "==========================================="
echo ""
echo "COMANDOS PARA DEPLOY:"
echo "---------------------"
echo ""
echo "git add sheets-funciones-corregidas.js sheets-lectura-datos.js"
echo ""
echo 'git commit -m "Fix: Normalización correcta de números WhatsApp'
echo ""
echo "- Quita +51 al guardar y buscar"
echo "- Solo guarda números: 936934501"
echo "- Compatibilidad con números ya guardados"
echo '- Búsquedas funcionan correctamente"'
echo ""
echo "git push heroku main"
echo ""
echo "==========================================="
echo ""
echo "DESPUÉS DEL DEPLOY:"
echo "-------------------"
echo ""
echo "1. Los NUEVOS pedidos se guardarán sin +51"
echo "2. Para pedidos EXISTENTES: cambiar manualmente en Sheets"
echo "3. El bot encontrará todos los pedidos correctamente"
echo ""
echo "==========================================="
